export default {
  GET_TASKS_REQUEST: "GET_TASKS_REQUEST",
  GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
  GET_TASKS_ERROR: "GET_TASKS_ERROR",
  ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_ERROR: "ADD_TASK_ERROR",
  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_ERROR: "DELETE_TODO_ERROR",
  CHANGE_PRIOTITY_REQUEST: "CHANGE_PRIORITY_REQUEST",
  CHANGE_PRIORITY_SUCCESS: "CHANGE_PRIORITY_SUCCESS",
  CHANGE_PRIORITY_ERROR: "CHANGE_PRIORITY_ERROR",
  EDIT_TASK_REQUEST: "EDIT_TASK_REQUEST",
  EDIT_TASK_SUCCESS: "EDIT_TASK_SUCCESS",
  EDIT_TASK_ERROR: "EDIT_TASK_ERROR",

  // modal action
  MODAL_NEWTASK_OPEN: "MODAL_NEWTASK_OPEN",
  MODAL_NEWTASK_CLOSE: "MODAL_NEWTASK_CLOSE",
};
